# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61bf28e356b4a84838461c3594e648b5b586a3a61b2d068319a277334ee7b1c20469e1ebac84ce9bcd7fc466b8170995d1ada4c571d2f5243131ea76e6cdaeb

test:
  secret_key_base: cd0fb6f3be121cec4b3c17c23225be0875404338ca7a78b94f939d89a5fb0b568a58a9afe4b56d5feff34a6031a234eac41dc0ca11f78a94070ecace71dde651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
